ARG BASE_IMAGE=koide3/gtsam_docker:jammy_cuda12.2

FROM ${BASE_IMAGE}

ARG BUILD_WITH_TBB=ON

COPY . /root/gtsam_points
WORKDIR /root/gtsam_points/build
RUN rm -rf *
RUN cmake .. \
  -DBUILD_DEMO=ON \
  -DBUILD_TESTS=ON \
  -DBUILD_EXAMPLE=ON \
  -DBUILD_TOOLS=ON \
  -DBUILD_WITH_TBB=${BUILD_WITH_TBB} \
  -DBUILD_WITH_CUDA=ON \
  -DBUILD_WITH_CUDA_MULTIARCH=ON \
  -DCMAKE_BUILD_TYPE=Release && \
  make -j$(nproc) && \
  make install && \
  rm -rf /root/gtsam_points/build

CMD ["bash"]
