var searchData=
[
  ['imu_0',['imu',['../classgtsam__points_1_1ContinuousTrajectory.html#a383323d30383df793baaab9500d870ce',1,'gtsam_points::ContinuousTrajectory::imu(const gtsam::Values &amp;values, double t, const Eigen::Vector3d &amp;g=Eigen::Vector3d(0.0, 0.0, 9.80665))'],['../classgtsam__points_1_1ContinuousTrajectory.html#a5c8f9331e385100cd7b3fc4abe2abb16',1,'gtsam_points::ContinuousTrajectory::imu(double t, const gtsam::Double_ &amp;t_, const Eigen::Vector3d &amp;g=Eigen::Vector3d(0.0, 0.0, 9.80665))']]],
  ['incrementalcovariancecontainer_1',['IncrementalCovarianceContainer',['../structgtsam__points_1_1IncrementalCovarianceContainer.html#a6aaa4d85b5af7690dbee11204816a4dc',1,'gtsam_points::IncrementalCovarianceContainer']]],
  ['incrementalcovariancevoxelmap_2',['IncrementalCovarianceVoxelMap',['../structgtsam__points_1_1IncrementalCovarianceVoxelMap.html#add6cdaa1562d78590f55c1fc16b72c3e',1,'gtsam_points::IncrementalCovarianceVoxelMap']]],
  ['incrementalvoxelmap_3',['IncrementalVoxelMap',['../structgtsam__points_1_1IncrementalVoxelMap.html#a985e94ab0de7517bcb597f925fb34da8',1,'gtsam_points::IncrementalVoxelMap']]],
  ['indexedslidingwindow_4',['IndexedSlidingWindow',['../classgtsam__points_1_1IndexedSlidingWindow.html#a789db821d2fd74090dbe02165d895e12',1,'gtsam_points::IndexedSlidingWindow']]],
  ['inlier_5ffraction_5',['inlier_fraction',['../classgtsam__points_1_1IntegratedGICPFactor__.html#a1d79191611a7ce47a7aa713b7fe9946b',1,'gtsam_points::IntegratedGICPFactor_::inlier_fraction()'],['../classgtsam__points_1_1IntegratedVGICPFactor__.html#aea67fe02d059d9e75fa3a103e3319e6d',1,'gtsam_points::IntegratedVGICPFactor_::inlier_fraction()'],['../classgtsam__points_1_1IntegratedVGICPFactorGPU.html#ad961a4c21cc74d8ec02fb836295ee4a8',1,'gtsam_points::IntegratedVGICPFactorGPU::inlier_fraction()']]],
  ['insert_6',['insert',['../structgtsam__points_1_1IncrementalVoxelMap.html#a4e8f10d43973d573b1e5bd99ba91dcc0',1,'gtsam_points::IncrementalVoxelMap::insert()'],['../classgtsam__points_1_1GaussianVoxelMapGPU.html#aa6c4489a0c885b95da1066ff7a5283a3',1,'gtsam_points::GaussianVoxelMapGPU::insert()'],['../classgtsam__points_1_1GaussianVoxelMapCPU.html#a1b3e2320eb0277a07579e1c0ad9b3f1b',1,'gtsam_points::GaussianVoxelMapCPU::insert()'],['../classgtsam__points_1_1GaussianVoxelMap.html#a358221ea7cd675c7cab4648612f29e77',1,'gtsam_points::GaussianVoxelMap::insert()'],['../structgtsam__points_1_1IncrementalCovarianceVoxelMap.html#ac989a7bd9d2245cd621bf3774390a915',1,'gtsam_points::IncrementalCovarianceVoxelMap::insert()'],['../classgtsam__points_1_1FastOccupancyGrid.html#a8aebb67be032166a42e9e882bd3cdc58',1,'gtsam_points::FastOccupancyGrid::insert()']]],
  ['integratedcolorconsistencyfactor_5f_7',['integratedcolorconsistencyfactor_',['../classgtsam__points_1_1IntegratedColorConsistencyFactor__.html#ac7f7859f61afdf9420dba98b4281017b',1,'gtsam_points::IntegratedColorConsistencyFactor_::IntegratedColorConsistencyFactor_(gtsam::Key target_key, gtsam::Key source_key, const std::shared_ptr&lt; const TargetFrame &gt; &amp;target, const std::shared_ptr&lt; const SourceFrame &gt; &amp;source, const std::shared_ptr&lt; const NearestNeighborSearch &gt; &amp;target_tree, const std::shared_ptr&lt; const IntensityGradients &gt; &amp;target_gradients)'],['../classgtsam__points_1_1IntegratedColorConsistencyFactor__.html#a862fcf9507d5c555e936edc1161b5205',1,'gtsam_points::IntegratedColorConsistencyFactor_::IntegratedColorConsistencyFactor_(const gtsam::Pose3 &amp;fixed_target_pose, gtsam::Key source_key, const std::shared_ptr&lt; const TargetFrame &gt; &amp;target, const std::shared_ptr&lt; const SourceFrame &gt; &amp;source, const std::shared_ptr&lt; const NearestNeighborSearch &gt; &amp;target_tree, const std::shared_ptr&lt; const IntensityGradients &gt; &amp;target_gradients)']]],
  ['integratedct_5fgicpfactor_5f_8',['integratedct_gicpfactor_',['../classgtsam__points_1_1IntegratedCT__GICPFactor__.html#a27e142ced7792ebec54f5232e660b8e4',1,'gtsam_points::IntegratedCT_GICPFactor_::IntegratedCT_GICPFactor_(gtsam::Key source_t0_key, gtsam::Key source_t1_key, const std::shared_ptr&lt; const TargetFrame &gt; &amp;target, const std::shared_ptr&lt; const SourceFrame &gt; &amp;source, const std::shared_ptr&lt; const NearestNeighborSearch &gt; &amp;target_tree)'],['../classgtsam__points_1_1IntegratedCT__GICPFactor__.html#a08012f2a81ce567f20755c7ec40e62f5',1,'gtsam_points::IntegratedCT_GICPFactor_::IntegratedCT_GICPFactor_(gtsam::Key source_t0_key, gtsam::Key source_t1_key, const std::shared_ptr&lt; const TargetFrame &gt; &amp;target, const std::shared_ptr&lt; const SourceFrame &gt; &amp;source)']]],
  ['integratedct_5ficpfactor_5f_9',['integratedct_icpfactor_',['../classgtsam__points_1_1IntegratedCT__ICPFactor__.html#a166fb1fc2d4e3b32239434a442eff0a8',1,'gtsam_points::IntegratedCT_ICPFactor_::IntegratedCT_ICPFactor_(gtsam::Key source_t0_key, gtsam::Key source_t1_key, const std::shared_ptr&lt; const TargetFrame &gt; &amp;target, const std::shared_ptr&lt; const SourceFrame &gt; &amp;source, const std::shared_ptr&lt; const NearestNeighborSearch &gt; &amp;target_tree)'],['../classgtsam__points_1_1IntegratedCT__ICPFactor__.html#afa550a452e5ccc589087ef2d703ab82d',1,'gtsam_points::IntegratedCT_ICPFactor_::IntegratedCT_ICPFactor_(gtsam::Key source_t0_key, gtsam::Key source_t1_key, const std::shared_ptr&lt; const TargetFrame &gt; &amp;target, const std::shared_ptr&lt; const SourceFrame &gt; &amp;source)']]],
  ['integratedgicpfactor_5f_10',['integratedgicpfactor_',['../classgtsam__points_1_1IntegratedGICPFactor__.html#a02f7dd0fe1e621c7e8531bbb66d0f92e',1,'gtsam_points::IntegratedGICPFactor_::IntegratedGICPFactor_(gtsam::Key target_key, gtsam::Key source_key, const std::shared_ptr&lt; const TargetFrame &gt; &amp;target, const std::shared_ptr&lt; const SourceFrame &gt; &amp;source, const std::shared_ptr&lt; const NearestNeighborSearch &gt; &amp;target_tree)'],['../classgtsam__points_1_1IntegratedGICPFactor__.html#aeebc478224a72243248fb7757c343d04',1,'gtsam_points::IntegratedGICPFactor_::IntegratedGICPFactor_(const gtsam::Pose3 &amp;fixed_target_pose, gtsam::Key source_key, const std::shared_ptr&lt; const TargetFrame &gt; &amp;target, const std::shared_ptr&lt; const SourceFrame &gt; &amp;source, const std::shared_ptr&lt; const NearestNeighborSearch &gt; &amp;target_tree)']]],
  ['integratedicpfactor_5f_11',['integratedicpfactor_',['../classgtsam__points_1_1IntegratedICPFactor__.html#a3c026140bb8a0860fbcdfa56ea874913',1,'gtsam_points::IntegratedICPFactor_::IntegratedICPFactor_(gtsam::Key target_key, gtsam::Key source_key, const std::shared_ptr&lt; const TargetFrame &gt; &amp;target, const std::shared_ptr&lt; const SourceFrame &gt; &amp;source, const std::shared_ptr&lt; const NearestNeighborSearch &gt; &amp;target_tree, bool use_point_to_plane=false)'],['../classgtsam__points_1_1IntegratedICPFactor__.html#ad2316dceba23668ece545e29d803b4f4',1,'gtsam_points::IntegratedICPFactor_::IntegratedICPFactor_(gtsam::Key target_key, gtsam::Key source_key, const std::shared_ptr&lt; const TargetFrame &gt; &amp;target, const std::shared_ptr&lt; const SourceFrame &gt; &amp;source, bool use_point_to_plane=false)'],['../classgtsam__points_1_1IntegratedICPFactor__.html#a5eb96d333d3424d17a57dcbd61d15b83',1,'gtsam_points::IntegratedICPFactor_::IntegratedICPFactor_(const gtsam::Pose3 &amp;fixed_target_pose, gtsam::Key source_key, const std::shared_ptr&lt; const TargetFrame &gt; &amp;target, const std::shared_ptr&lt; const SourceFrame &gt; &amp;source, const std::shared_ptr&lt; const NearestNeighborSearch &gt; &amp;target_tree, bool use_point_to_plane=false)'],['../classgtsam__points_1_1IntegratedICPFactor__.html#a98f39fa3e70ea482f8f634d64fab2a8a',1,'gtsam_points::IntegratedICPFactor_::IntegratedICPFactor_(const gtsam::Pose3 &amp;fixed_target_pose, gtsam::Key source_key, const std::shared_ptr&lt; const TargetFrame &gt; &amp;target, const std::shared_ptr&lt; const SourceFrame &gt; &amp;source, bool use_point_to_plane=false)']]],
  ['integratedmatchingcostfactor_12',['integratedmatchingcostfactor',['../classgtsam__points_1_1IntegratedMatchingCostFactor.html#af505d5844b254cd7eceac3bf1104d1ca',1,'gtsam_points::IntegratedMatchingCostFactor::IntegratedMatchingCostFactor(gtsam::Key target_key, gtsam::Key source_key)'],['../classgtsam__points_1_1IntegratedMatchingCostFactor.html#a28a6f1db179922a4c3346f28375314a3',1,'gtsam_points::IntegratedMatchingCostFactor::IntegratedMatchingCostFactor(const gtsam::Pose3 &amp;fixed_target_pose, gtsam::Key source_key)']]],
  ['integratedvgicpfactor_5f_13',['integratedvgicpfactor_',['../classgtsam__points_1_1IntegratedVGICPFactor__.html#aa0da757ad6199a3ce3c8ffaac9df6aa1',1,'gtsam_points::IntegratedVGICPFactor_::IntegratedVGICPFactor_(gtsam::Key target_key, gtsam::Key source_key, const GaussianVoxelMap::ConstPtr &amp;target_voxels, const std::shared_ptr&lt; const SourceFrame &gt; &amp;source)'],['../classgtsam__points_1_1IntegratedVGICPFactor__.html#ab889dee5676e0771c84338e2a62aebc9',1,'gtsam_points::IntegratedVGICPFactor_::IntegratedVGICPFactor_(const gtsam::Pose3 &amp;fixed_target_pose, gtsam::Key source_key, const GaussianVoxelMap::ConstPtr &amp;target_voxels, const std::shared_ptr&lt; const SourceFrame &gt; &amp;source)']]],
  ['integratedvgicpfactorgpu_14',['integratedvgicpfactorgpu',['../classgtsam__points_1_1IntegratedVGICPFactorGPU.html#a163bad933efb590ca20cb2cf36c77e58',1,'gtsam_points::IntegratedVGICPFactorGPU::IntegratedVGICPFactorGPU(gtsam::Key target_key, gtsam::Key source_key, const GaussianVoxelMap::ConstPtr &amp;target, const PointCloud::ConstPtr &amp;source, CUstream_st *stream=nullptr, std::shared_ptr&lt; TempBufferManager &gt; temp_buffer=nullptr)'],['../classgtsam__points_1_1IntegratedVGICPFactorGPU.html#a7961401cc8c994c036588a44d9837617',1,'gtsam_points::IntegratedVGICPFactorGPU::IntegratedVGICPFactorGPU(const gtsam::Pose3 &amp;fixed_target_pose, gtsam::Key source_key, const GaussianVoxelMap::ConstPtr &amp;target, const PointCloud::ConstPtr &amp;source, CUstream_st *stream=nullptr, std::shared_ptr&lt; TempBufferManager &gt; temp_buffer=nullptr)']]],
  ['intensitykdtree_15',['IntensityKdTree',['../structgtsam__points_1_1IntensityKdTree.html#afc8cba8eff515fe46e0d3010a3a03256',1,'gtsam_points::IntensityKdTree']]],
  ['issue_5fcompute_5ferror_16',['issue_compute_error',['../classgtsam__points_1_1IntegratedVGICPFactorGPU.html#a0ac1f590f997e808ffa10281e3d37ead',1,'gtsam_points::IntegratedVGICPFactorGPU::issue_compute_error()'],['../classgtsam__points_1_1NonlinearFactorGPU.html#a9ac2cb94a6a72b044140a40bc60bd7d5',1,'gtsam_points::NonlinearFactorGPU::issue_compute_error()']]],
  ['issue_5flinearize_17',['issue_linearize',['../classgtsam__points_1_1IntegratedVGICPFactorGPU.html#a257644ad2e816fb6349899c505559735',1,'gtsam_points::IntegratedVGICPFactorGPU::issue_linearize()'],['../classgtsam__points_1_1NonlinearFactorGPU.html#a846e748369b9b4a9c82fa94ae1478973',1,'gtsam_points::NonlinearFactorGPU::issue_linearize()']]]
];
